helm-maintainers-onboarding-guide.md

Note, much of this was written by other members of the helm team (e.g.,
Matt Buther) who have given their permission and/or direction for
this document to be placed here.
cc @technosophos @michelleN @adamreese @bacongobbler @jascott1 @nebril @prydonius @SlickNik @thomastaylor312 @viglesiasce 
FYI @parispittman

Initial addition of helm maintainers onboarding guide

---

user-profiles.md

At the Helm Summit I took on the task of documenting the user profiles (similar to personas but categories instead of example actors). This is my first cut of that which is ready for review.
cc @kubernetes-helm/helm-core-maintainers

Adding initial user profiles

---

helm-v3/deisgn-proposal.md

Overlays turn out to not be necessary if there is Lua support and a
post-render event.

Helm 3 proposal: Remove overlays

---

helm-v3/deisgn-proposal.md

That part of the proposal is actually unrelated to the functionality of
Helm 3. We will still integration with an Application object if one is
ever standardized. However, it need not be part of the proposal.

Remove the section on Application Object

---

helm-v3/deisgn-proposal.md

Contrast this with #7.
There seems to be no point in representing a Chart.yaml as a Kubernetes resource. So this PR simply removes that part of the proposal.

Remove chart.yaml changes

---

helm-v3/001-charts.md
helm-v3/002-events.md

This is a result of some work on @prydonius's question about library
charts and Lua. The change here is that there is only one Lua
interpreter for a chart operation. So if a parent chart has three
subcharts, there is only one Lua interpreter and it has access to all
four charts.
This change allows two things:
- library charts with Lua
- explicit override control for a top-level chart

Change the Lua sandbox model for charts.

---

helm-v3/001-charts.md

We will only load `chart.lua`. Also, specify that it is `io`, not
`filesystem`, that provides filesystem access.

Fix description of how Lua is loaded.

---

proposals/distributed-search.md

cc: @prydonius @unguiculus @technosophos @michelleN 
The best correlation I have to this is packagist for PHP.
Please nit as this is a draft.

Adding distributed search proposal

---

helm-v3/002-events.md

Reference right script location for the `chart.lua` script

Helm 3: Fix wrong chart lua-script path

---

governance/governance.md

Fixes small typo for `governance.md`.

Fix typos on governance doc

---

README.md
helm-maintainers-onboarding-guide.md

Looking through the documentation, there are references to a `starter` label, which does not seem to exist anymore. Instead, it looks like the `starter` tag has been replaced with `good first issue`; this pull request addresses this change and updates the references to link to the proper location.
Signed-off-by: Panic Stevenson <panic.stevenson@gmail.com>

Updating "Starter" Label References to "Good First Issue"

---

Teams.md

For the two projects that do not have documented lists of teams there are now open issues to add them.
This is the output of an action item I took in one of the Helm Developer Weekly calls.

Adding list of different Helm project teams

---

SECURITY.md

Justing has moved to emeritus status and is no longer actively
maintaining Helm. Verified with him prior to removal.

Removed Justin Scott from security process

---

governance/governance.md

The existing wording focused on technical codebases and did not
appear to provide room for a project dealing with community
management or any other non-technical project.
This change opens the door for projects that are not technical in
nature. It is added at this point to support community management
which has happened for a long time but has not been recognized or
empowered the way other projects have been. I hope that recognizing
the work and officially empowering it helps to expand the effort
and grow help usage and contributors.
Note, this cannot be merged until a super-majority of the org maintainers vote on it.

Broaden the scope of a helm subproject to include non-tech projects

---

communication.md

I noticed the website (which links to this page on github) lacked a link to the videos for the community meetings.

Adding video link

---

communication.md

Fixes https://github.com/helm/community/issues/83
The Slack archive tool referenced in this doc is deprecated without a replacement.

Removing defunct link

---

communication.md

I noticed https://github.com/helm/community/issues/115 and it made me realize that our docs talk about our channels on the Kubernetes Slack but do not tell people how to join that Slack. 
Also, I noticed some http links which can now be https.

Clarifying how to join Slack; adding https.

---

README.md
art/readme.md

Helm logos link wasn't updated once the project moved from incubating to graduated.

Fixed location of helm logos

---

hips/hip-0002.md
hips/hip-9999.md

Replaces #141 
The idea is to have a well-known release cadence for the helm minor releases.
In my experience contributors and users greatly appreciate knowing in advance when the next release will be available.
It allows contributors to plan their work, avoids disappointing delays and provides users with clear timelines for access to bug fixes and features.
Please see details in the HIP document, which can be read nicely formatted here: https://github.com/VilledeMontreal/community/blob/feat/fixedDates/hips/hip-9999.md

HIP 0002: Announced release dates

---

governance/governance.md

When the first Helm Org Maintainers election occurred there were
criteria laid out to ensure sub-project diversity at that time.
This section of the governance was only for that initial election
and did not apply after the initial election.
As that election was years ago and the governance is stored in
git, this PR removes this section as it is no longer relevant.
This requires 2/3 vote from the org maintainers (6 approves including myself) prior to being merged.

Removing initial election details from governance

---

hips/hip-0002.md

Thinking about  HIP 0002 and published release dates, I realized we also need a page to describe to the community how we will handle dates, alike Kubernetes page: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#minor-version-scheme-and-timeline
This commit updates the HIP to include this aspect.
It also fixes #160

Add requirement for reference implementation of HIP 0002

---

hips/hip-0008.md
hips/hip-9999.md

This HIP is a proposal to add descriptions to helm's custom completions.
For quick access: https://github.com/VilledeMontreal/community/blob/hip/compCustomDescriptions/hips/hip-0008.md
For example:
```
$ helm history n<TAB>
nginx   -- nginx-6.0.2 -> deployed
nginx2  -- nginx-ingress-1.41.2 -> deployed
```
instead of simply:
```
$ helm history n<TAB>
nginx  nginx2
```
I wasn't sure a HIP was really necessary, however having one (assuming it is accepted), will make it easier to get input on the information that should be added to each type of completion (see the [Specifications section](https://github.com/VilledeMontreal/community/blob/hip/compCustomDescriptions/hips/hip-0008.md#specification)).
Note that such support would apply to `zsh` and `fish` shells, as `bash` does not (currently) …

HIP for descriptions for custom completions

---

README.md
Teams.md
communication.md
helm-maintainers-onboarding-guide.md

The default branch has been changed to `main`
Signed-off-by: Adam Reese <adam@reese.io>

fix(*): use correct branch for helm repo

---

architecture/crds.md
hips/hip-0011.md

This is a draft of a document to provide a complete explanation of the CRD conundrum in Helm. The intention is to have one formal statement that we can direct others to so that they understand:
- The nature of the problem
- The reason for Helm's current implementation
- The guidelines for future alternatives
- The time frame for reconsidering our design choices
Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>

HIP-0011: Informational Helm CRD HIP

---

hips/hip-0001.md
hips/hip-0002.md
hips/hip-0003.md
hips/hip-0006.md
hips/hip-0008.md

When pushing HIP 0010 I realized the markdown was showing `8` instead.  After some head-scratching, page-reloading and browser-cache-emptying, I realized that the markdown was interpreting the string `0010` as octal because it was not surrounded by quotes.
To align all HIPs, any of which could be used as an example to create a new one, this PR adds quotes to all such strings.
Using decimal digits as was originally done for HIP 1 would also fix the problem; however, since hip 1 named its HIP file `hip-0001.md`, all other hips adopted the full `00xx` format.

Add quotes to avoid octal interpretation

---

MAINTAINERS.md

He did so via the public mailing list at
https://lists.cncf.io/g/cncf-helm/message/376

Moving Vic to Emeritus

---

SECURITY.md

The security team membership requires someone to be an active
maintainer on a project. Vic is not longer an active maintainer
so he is no longer able to be on this team.

Removing Vic from the security team

---

governance/README.md
governance/governance.md
helm-maintainers-onboarding-guide.md

Maintainer info as seen in current reality (as I understand it) has drifted from what was previously written here. This PR attempts to update the docs to match the current practices. Changes:
- Clarifies that governance is under the CNCF rather than the Kubernetes project
- Tiller is gone
- Monocular is being retired
- De-emphasizes maintaining of specific charts in and of themselves; instead, emphasizes charts-related tooling
- Corrects small details about which bots are used for what
- Links specific version skew doc
- Adds references to specific HIPs where practices have been codified
- Changes some nuance around language that seems to date to the project being brand-new
Input/edits welcome.

Updating maintainer info

---

MAINTAINERS.md

For review by @technosophos, org chair.

Add Martin as org maintainer

---

hips/hip-0010.md
hips/hip-9999.md

The HIP can be read nicely at https://github.com/VilledeMontreal/community/blob/hip/pickprocess/hips/hip-0010.md
The picking of PRs into a release branch is currently the responsibility of the maintainer cutting the release. It is usually the largest part of cutting a release. Improving the picking process would make cutting releases easier with a reduced risk of error.
This HIP proposes to distribute the picking responsibility to each maintainer that merged a PR.

HIP-0010: distributed pick process

---

hips/hip-0014.md

As triage maintainers do not have voting rights, they cannot join the core maintainers mailing list, as that is where all voting occurs.
This was overlooked after we concluded a discussion in https://github.com/helm/community/pull/199#discussion_r686914309. This was discovered during the onboarding process of a new triage maintainer.
Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

remove "receive access to helm-core-maintainers" mailing list

---

MAINTAINERS.md
SECURITY.md

Thanks, @prydonius! Moving you to emeritus per @technosophos.
Associated PRs:
https://github.com/helm/helm-2to3/pull/197
https://github.com/helm/charts/pull/24541
https://github.com/helm/helm/pull/10470

Moving prydonius to emeritus

---

MAINTAINERS.md

This adds @karenhchu as a Helm org maintainer.
Signed-off-by: Matt Butcher <matt.butcher@fermyon.com>

Per the conclusion of the vote on Jan 10, add Karen Chu

---

meeting-notes/2021.txt

Moving the 2021 meeting notes from our google doc to this archive.
Once merged, I will cleanup the google doc: https://docs.google.com/document/d/1d-6xJEx0C78csIYSPKJzRPeWaHG_8W1Hjl72OJggwdc

Add meeting nodes for 2021

---

hips/hip-0015.md

This HIP identifies how a chart can describe the images needed by a chart for deployment for use in airgap deployments, SBOMs or general metadata.

HIP for Identifying Images for Helm Chart 

---

stable-repo-charts-new-locations.md

closes #232 
Moved issue, now moving to a file so the community can help maintain this through PRs.
I may have explained a bit too much here. Will happily take any suggestions for editing this down. Main thing is this issue still serves a purpose, so moved it. Then realized the table in the issue itself was behind at times, because I was the main peson updating it, but end users can make PRs against a file 😅 
- Today's Helm dev meeting action item this relates to:
https://docs.google.com/document/d/1d-6xJEx0C78csIYSPKJzRPeWaHG_8W1Hjl72OJggwdc/edit#heading=h.ayp8tsp2dvg6
- Original issue: https://github.com/helm/charts/issues/21103
- New issue location: https://github.com/helm/community/issues/232

Move stable/charts issue to file, to help community relocate charts to new repos

---

hips/README.md

HIP file names indicate the HIP number.  Remembering which HIP number
represents which proposal is difficult.  Having the title of the HIP
listed in the README should make finding the correct HIP easier.
The disadvantage is of course that this list must be maintained.

Add a list of HIPs to the README

---

hips/hip-0004.md

Exposing Kubernetes APIs is a place where Helm cannot enforce
backwards compatibility. K8s does not follow semantic versioning.
Making this explicit.

Adding an exception to back compat

---

hips/hip-9999.md

Signed-off-by: Andy Suderman <andy@suderman.dev>
I have talked to @lucasreed and he currently doesn't have the time to take this HIP forward further. We agreed that I could branch off of his implementation, and address any comments as well as rebasing the branch. This is the result.
Original PR - https://github.com/helm/community/pull/224#
> Opening this HIP after conversation with @mattfarina in this PR comment section: https://github.com/helm/helm/pull/10369
> This would help solve this longstanding issue: https://github.com/helm/helm/issues/4256

HIP to include repository URL and tarball digest in release object under chart metadata

---

hips/hip-0016.md
hips/hip-9999.md

> Composing Helm charts using dependencies is currently limited because it is not possible to create a chart with a defined set of values and distribute them to subcharts.
This hip proposes an `export-values` structure to address this issue.

hip introducing  `export-values` for better composability

---

hips/hip-0011.md

According to the description in [document](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you), and the implementation in [source code](https://github.com/helm/helm/blob/46103aa1df0388d07444f25e0688ffe946812ebe/pkg/chart/chart.go#L158), I think the directory name here should be `crds`

fix directory name in docs hip-0011

---

hips/hip-0012.md

Hello,
I am codifying that Matt Farina is the release engineer for Helm 4.

adding matt as named release enginneer

---

hips/README.md
hips/hip-0019.md
hips/hip-9999.md

This proposes a new annotation to indicate that the output from the job should be displayed to the user. This is mostly already implemented in:
https://github.com/helm/helm-www/pull/1242
https://github.com/helm/helm/pull/10309

Add HIP for obtaining output from hook jobs and pods

---

hips/README.md
hips/hip-0020.md

This HIP outlines creating a new chart version of v3 to enable some more radical changes without disrupting current charts and the Helm 4 timeline.

H4HIP: Adding a HIP on charts v3
