- helm-v3-user-stories.md
These are pulled from information collected at the helm summit. Note, for those who think these are familiar... they did start their life in a hackmd but where moved here and put into the current user profiles.
cc @kubernetes-helm/helm-core-maintainers
> Initial addition of helm v3 user stories

- helm-v3/deisgn-proposal.md
Allow finer grained permissions controls for Lua libraries
h/t to @kfox1111 for this idea
> Add --accept-perms flag

- helm-v3/deisgn-proposal.md
h/t @kfox1111 for this suggestion
> Clarify that release names are now namespaced.

- helm-v3/deisgn-proposal.md
It has been noted a few times that CRDs cannot protect data effectively,
and so a Secret should be used to store sensitive information.
> Change ReleaseVersion CRD to release version Secret

- helm-v3/005-plugins.md
This explains changes to the old plugin system as well as brief
information on how Lua plugins will be executed.
> Update plugins document to describe technical changes

- helm-v3/002-events.md
This clarifies the Helm 3 proposal with some of our learning during POC work.
/cc @adamreese - There's one comment in there intended for you. We had talked about it, but I can't remember the answer.
> Major update to events section of Helm 3 plan

- governance/provisional-governance.md
This includes the current voting members.
> Initial add of the provisional governance document

- README.md
- communication.md
A few initial steps to fix https://github.com/helm/community/issues/31
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
> Helm community info updated

- helm-v3/006-repositories.md
/cc @technosophos @jdolitsky 
This is currently WIP and I will be cleaning up the language and adding more to this. Thoughts on the idea?
> Helm Repositories v2

- proposals/monocular-1.0-improvements.md
Describes improvements and changes to be made, and redefines project to support the CNCF Helm Hub.
cc @mattfarina @technosophos @michelleN
> Adding Monocular 1.0 proposal

- README.md
Signed-off-by: Sean Scott <sts423@gmail.com>
> Replace CLA with DCO in README

- communication.md
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
> Helm's tag on Stack Overflow corrected

- README.md
- communication.md
> Improve on getting started for new members

- governance/governance.md
closes #73 
Signed-off-by: Radu Matei <radu@radu-matei.com>
> Fix escalation error in governance doc and a typo

- communication.md
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
> Minor fix - communication.md

- README.md
Signed-off-by: Karen Chu <karen.chu@microsoft.com>
> adding in Twitter info

- communication.md
Signed-off-by: Karen Chu <karen.chu@microsoft.com>
> adding Helm Summit EU 2019 info

- README.md
Adds links to the latest helm logos
> add links to readme

- communication.md
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
> Helm Summit 2019 info updated

- meeting-notes.txt
closes #108 
Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>
> add meeting notes

- README.md
Adding the intended link to the README.
> Adding missing slides link

- SECURITY.md
Michelle has stepped down from her Helm responsibilities.
Removing her from the security team as part of her
off-boarding process.
> Removing Michelle Noorali from security team

- blog-topics.md
Signed-off-by: Karen Chu <karen.chu@microsoft.com>
> Add suggestions for Helm 2 to 3 Migration Topics

- communication.md
> Updating link for Zoom call

- hips/hip-0003.md
As requested in https://github.com/helm/community/pull/142#pullrequestreview-485194085, I have copied @technosophos's content into the requested format. Edits appreciated.
> Adding HIP 0003

- README.md
- slides/README.md
Helm Community repository default branch is now `main`
> fix(*): update default branch name

- helm-maintainers-onboarding-guide.md
Signed-off-by: Adam Reese <adam@reese.io>
> fix(*): fix misspellings

- hips/hip-0012.md
- hips/hip-9999.md
This is a draft proposal for how Helm 4 development can proceed.
Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>
> HIP for Helm 4 planning and development process

- hips/hip-0014.md
This has been asked a few times, so I thought I'd drop it in the document to make it clear for those reading through HIP 14.
> Add more details on the nomination/voting process for Triage Maintainers

- SECURITY.md
Signed-off-by: Martin Hickey martin.hickey@ie.ibm.com
> Add Martin Hickey to the security team

- SECURITY.md
> Add myself to security team

- hips/hip-9999.md
Informational HIP to register Helm OCI media types with IANA
fixes: https://github.com/helm/community/issues/248
closes: #249
> HIP: Helm OCI MediaType registration

- hips/README.md
- hips/hip-0016.md
- hips/hip-0017.md
Follow-up to fix https://github.com/helm/community/pull/255#issuecomment-1178225503
> Increment HIP number from most recent

- hips/hip-0001.md
Signed-off-by: Scott Rigby <scott@r6by.com>
> Move HIP 0001 to accepted

- hips/hip-0002.md
- hips/hip-0003.md
- hips/hip-0004.md
- hips/hip-0006.md
- hips/hip-0008.md
- hips/hip-0014.md
- hips/hip-0017.md
Per today's Helm dev meeting
Signed-off-by: Scott Rigby <scott@r6by.com>
> Document accepted HIPs as such

- MAINTAINERS.md
> Move Adam Reese to emeritus

- MAINTAINERS.md
> Move Matt Fisher to emeritus

- MAINTAINERS.md
- SECURITY.md
Ref email: https://lists.cncf.io/g/cncf-helm/message/496
> Move jdolitsky to emeritus

- hips/hip-0018.md
> Fix missing quote in HIP-18

- hips/README.md
- hips/hip-0022.md
> Updating kstatus HIP to have a number

- hips/hip-0021.md
just adding in how we are implementing slog.
> adding in the static example for impementing slog

- hips/hip-0022.md
This work was completed in https://github.com/helm/helm/pull/13604, but we kept the status in draft. I didn't find an official status list, but it seems like accepted is most common
> update status for HIP 22
